# Make a user key
# mkdir -p ~/.config/sops/age
# age-keygen -o ~/.config/sops/age/keys.txt
# chmod 600 ~/.config/sops/age/keys.txt

# Display the user public key:
# age-keygen -y ~/.config/sops/age/keys.txt

# Make a host public key:
# nix-shell -p ssh-to-age
# ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub

# Add secrets
# sops secrets/secrets.yaml

# Rekey secrets.yaml after editing recipients in .sops.yaml:
# sops updatekeys secrets/secrets.yaml
keys:
  - &users:
    - &alex age1ff98yfdlxax5ymnlu9rdzermuyvg8jwq98z6h86tpj8ajlxw7upsq4k8a0
  - &host:
    - &frostmourne age1kjqhsyucjhuw6gazjrjqcuavay6pfgpr8fasltft99vzfdkjdsdsvfx4xv
    - &palantir age1ajyn9l0v2fv5kyhdzvkr4dxw6rm602w06sk3qnxz5d7aj67ygy0qv4drf9
    - &sonic age1tksd8m2p4cup3mlknft7e7yrcyv0av5duyf2h0r4d2qza07ajgzqxe0h57
creation_rules:
  - path_regex: ^secrets/suites/kubernetes\.ya?ml$
    key_groups:
      - age:
          - *frostmourne
          - *alex
  - path_regex: ^secrets/hosts/palantir\.ya?ml$
    key_groups:
      - age:
          - *palantir
          - *alex

  - path_regex: ^secrets/hosts/sonic\.ya?ml$
    key_groups:
      - age:
          - *sonic
          - *alex
